export const ActionTypes = {
    CREATE_CART : "CREATE_CART",
    SET_CARTS : "SET_CARTS",
    SELECTED_CART : "SELECTED_CART",
    EDIT_CART : "EDIT_CART",
    UPDATE_QUANTITY: "UPDATE_QUANTITY", 
    DELETE_CART : "DELETE_CART",
}