export const ActionTypes = {
    CREATE_CATEGORY : "CREATE_CATEGORY", 
    SET_CATEGORIES : "SET_CATEGORIES",
    SELECTED_CATEGORY : "SELECTED_CATEGORY",
    EDIT_CATEGORY : "EDIT_CATEGORY",
    DELETE_CATEGORY : "DELETE_CATEGORY",
}