export const ActionTypes = {
    
    CREATE_PRODUCT:"CREATE_PRODUCT",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    MODAL_PRODUCT : "MODAL_PRODUCT",
    EDIT_PRODUCT : "EDIT_PRODUCT",
    DELETE_PRODUCT : "DELETE_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    REMOVE_MODAL_SELECTED_PRODUCT : "REMOVE_MODAL_SELECTED_PRODUCT",
    FILTER_PRODUCTS : "FILTER_PRODUCTS",
    SEARCH_PRODUCTS : "SEARCH_PRODUCTS"
    
}